#!/system/bin/sh

clear
echo "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓"
sleep 0.5
echo "✘PUBG MOBILE V.0.16.5✘"
sleep 0.5
echo "✘CREATOR : @XHIDROLIC✘"
sleep 0.5
echo "✘DEV MTP OFFICIAL✘"
sleep 0.5
echo "✘COPYRIGHT 2020 ©✘"
sleep 0.5
echo "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓"

mv /data/data/com.rekoo.pubgm/lib/libgcloud.so /storage/emulated/0/BahanCheat/libmod
mv /data/data/com.rekoo.pubgm/lib/libUE4.so /storage/emulated/0/BahanCheat/libmod
mv /data/data/com.rekoo.pubgm/lib/libzip.so /storage/emulated/0/BahanCheat/libmod
mv /data/data/com.rekoo.pubgm/lib/libzlib.so /storage/emulated/0/BahanCheat/libmod
mv /data/data/com.rekoo.pubgm/lib/libabase.so /storage/emulated/0/BahanCheat/libmod
mv /data/data/com.rekoo.pubgm/lib/libBugly.so /storage/emulated/0/BahanCheat/libmod

mv /storage/emulated/0/BahanCheat/libbackup/libgcloud.so /data/data/com.rekoo.pubgm/lib
mv /storage/emulated/0/BahanCheat/libbackup/libUE4.so /data/data/com.rekoo.pubgm/lib
mv /storage/emulated/0/BahanCheat/libbackup/libzip.so /data/data/com.rekoo.pubgm/lib
mv /storage/emulated/0/BahanCheat/libbackup/libzlib.so /data/data/com.rekoo.pubgm/lib
mv /storage/emulated/0/BahanCheat/libbackup/libabase.so /data/data/com.rekoo.pubgm/lib
mv /storage/emulated/0/BahanCheat/libbackup/libBugly.so /data/data/com.rekoo.pubgm/lib

chmod -R 755 /data/data/com.rekoo.pubgm/lib/libabase.so
chmod -R 755 /data/data/com.rekoo.pubgm/lib/libBugly.so
chmod -R 755 /data/data/com.rekoo.pubgm/lib/libgcloud.so
chmod -R 755 /data/data/com.rekoo.pubgm/lib/libUE4.so
chmod -R 755 /data/data/com.rekoo.pubgm/lib/libzip.so
chmod -R 755 /data/data/com.rekoo.pubgm/lib/libzlib.so

chmod 660 /data/data/com.rekoo.pubgm/databases/__hs__db_issues
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs__db_key_values
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs__db_properties
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs__db_sessions
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs__db_support_key_values
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs_db_helpshift_users
chmod 660 /data/data/com.rekoo.pubgm/databases/__hs_log_store
chmod 660 /data/data/com.rekoo.pubgm/databases/bugly_db_
chmod 660 /data/data/com.rekoo.pubgm/databases/config.db
chmod 660 /data/data/com.rekoo.pubgm/databases/google_app_measurement_local.db
chmod 660 /data/data/com.rekoo.pubgm/databases/iMSDK.db
chmod 660 /data/data/com.rekoo.pubgm/databases/tdm.db
chmod 771 /data/data/com.rekoo.pubgm/shared_prefs
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_137_0.16.5.11560_20200108102536_2026323150_cures.ifs.res
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.5.11560.pak
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_path_0.16.5.11860.pak
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.5.11560.pak
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_137_0.16.5.11560_20200108102536_2026323150_cures.ifs.res
chmod 660 /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.cures

rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/Tencent
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/cache
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/ca-bundle.pem 	  
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/tbslog  	  
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/cacheFile.txt	
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/vmpcloudconfig.json
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata?n??

rm -rf /data/data/com.rekoo.pubgm/app_appcache
rm -rf /data/data/com.rekoo.pubgm/cache
rm -rf /data/data/com.rekoo.pubgm/code_cache
rm -rf /data/data/com.rekoo.pubgm/files/ss_tmp
rm -rf /data/data/com.rekoo.pubgm/files/tss_tmp
rm -rf /data/data/com.rekoo.pubgm/files/AppEventsLogger.persistedevents
rm -rf /data/data/com.rekoo.pubgm/files/tpnlcache.data
rm -rf /data/data/com.rekoo.pubgm/files/tss_app_915c.dat
rm -rf /data/data/com.rekoo.pubgm/files/tss_cs_stat2.dat
rm -rf /data/data/com.rekoo.pubgm/files/tss.i.m.dat
rm -rf /data/data/com.rekoo.pubgm/files/TAPM_CM_AUDIT
rm -rf /data/data/com.rekoo.pubgm/files/com.tencent.gcloud.gvoice
rm -rf /data/data/com.rekoo.pubgm/files/hawk_data_init

busybox echo -e "\e[00;41m       DONE        \e[00;37;40m"
